name: Build & Push Images (GHCR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # allow GITHUB_TOKEN to push to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase owner
        id: owner
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Backend image
      - name: Build & Push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ steps.owner.outputs.owner_lc }}/mern-backend:latest
            ghcr.io/${{ steps.owner.outputs.owner_lc }}/mern-backend:${{ steps.vars.outputs.SHORT_SHA }}

      # Frontend image
      - name: Build & Push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ steps.owner.outputs.owner_lc }}/mern-frontend:latest
            ghcr.io/${{ steps.owner.outputs.owner_lc }}/mern-frontend:${{ steps.vars.outputs.SHORT_SHA }}
